version: "3.7"

services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      bank_microservices:
        ipv4_address: 172.25.0.12

  keycloak_web:
    image: quay.io/keycloak/keycloak
    container_name: keycloak-web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USER: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ["start-dev", "--import-realm"]
    depends_on:
      - keycloakdb
    ports:
      - 8080:8080
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    networks:
      java_microservices:
        ipv4_address: 172.25.0.11

  keycloakdb:
    image: postgres
    container_name: keycloak_postgre_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      java_microservices:
        ipv4_address: 172.25.0.10

  mysql_core_db:
    build: mysql
    container_name: mysql_core_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      java_microservices:
        ipv4_address: 172.25.0.9

  internet-banking-config-server:
    image: my/internet-banking-config-server
    container_name: internet-banking-config-server
    ports:
      - 8090:8090
    networks:
      java_microservices:
        ipv4_address: 172.25.0.8

  internet-banking-service-registry:
    image: my/internet-banking-service-registry
    container_name: internet-banking-service-registry
    ports:
      - 8081:8081
    networks:
      java_microservices:
        ipv4_address: 172.25.0.7

  internet-banking-api-gateway:
    image: my/internet-banking-api-gateway
    container_name: internet-banking-api-gateway
    ports:
      - 8082:8082
    entrypoint: [ "./wait-for-it.sh", "internet-banking-service-registry:8081", "--timeout=50", "--", "./wait-for-it.sh", "internet-banking-config-server:8090", "--timeout=50", "--", "java", "-jar", "-Dspring.profiles.active=docker", "/app.jar" ]
    networks:
      java_microservices:
        ipv4_address: 172.25.0.6

  internet-banking-user-service:
    image: my/internet-banking-user-service
    container_name: internet-banking-user-service
    ports:
      - 8083:8083
    entrypoint: [ "./wait-for-it.sh", "internet-banking-service-registry:8081", "--timeout=50", "--", "./wait-for-it.sh", "internet-banking-config-server:8090", "--timeout=50", "--", "./wait-for-it.sh", "mysql_core_db:3306", "--timeout=50", "--","java", "-jar", "-Dspring.profiles.active=docker", "/app.jar" ]
    networks:
      java_microservices:
        ipv4_address: 172.25.0.5

  internet-banking-fund-transfer-service:
    image: my/internet-banking-fund-transfer-service
    container_name: internet-banking-fund-transfer-service
    ports:
      - 8084:8084
    entrypoint: [ "./wait-for-it.sh", "internet-banking-service-registry:8081", "--timeout=50", "--", "./wait-for-it.sh", "internet-banking-config-server:8090", "--timeout=50", "--", "./wait-for-it.sh", "mysql_core_db:3306", "--timeout=50", "--","java", "-jar", "-Dspring.profiles.active=docker", "/app.jar" ]
    networks:
      java_microservices:
        ipv4_address: 172.25.0.4

  internet-banking-utility-payment-service:
    container_name: internet-banking-utility-payment-service
    image: my/internet-banking-utility-payment-service
    ports:
      - 8085:8085
    entrypoint: [ "./wait-for-it.sh", "internet-banking-service-registry:8081", "--timeout=50", "--", "./wait-for-it.sh", "internet-banking-config-server:8090", "--timeout=50", "--", "./wait-for-it.sh", "mysql_core_db:3306", "--timeout=50", "--","java", "-jar", "-Dspring.profiles.active=docker", "/app.jar" ]
    networks:
      java_microservices:
        ipv4_address: 172.25.0.3

  core-banking-service:
    image: my/core-banking-service
    container_name: core-banking-service
    ports:
      - 8092:8092
    entrypoint: [ "./wait-for-it.sh", "internet-banking-service-registry:8081", "--timeout=50", "--", "./wait-for-it.sh", "internet-banking-config-server:8090", "--timeout=50", "--", "./wait-for-it.sh", "mysql_core_db:3306", "--timeout=50", "--","java", "-jar", "-Dspring.profiles.active=docker", "/app.jar" ]
    networks:
      java_microservices:
        ipv4_address: 172.25.0.2



volumes:
  postgres_data:
  mysql_data:


networks:
  bank_microservices:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
