server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://mysql_core_db:3306/banking_core_fund_transfer_service
    username: javatodev_development
    password: oPItyPticIAt
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://172.25.0.12:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://internet-banking-service-registry:8081/eureka

info:
  app:
    name: ${spring.application.name}