spring:
  application:
        name: internet-banking-server
  cloud:
    config:
          server:
            git:
              uri: https://github.com/JavatoDev-com/internet-banking-microservices-configurations.git
              search-paths: configuration
              default-label: main

server:
  port: 8090
#
